### ISSUE TITLE
Tasker not found error in very specific situation

### ISSUE THREAD

**Issue by Subtletree** [floraison/flor#30]
Using flor master.

Running into a strange issue with the below process. Is there a syntax error there I'm missing?

```ruby
ENV['FLOR_DEBUG'] = 'dbg,stdout'
STDOUT.sync = true

require 'pp'
require 'flor/unit'

FLOR = Flor::Unit.new(loader: Flor::HashLoader, sto_uri: 'sqlite:/')
FLOR.storage.delete_tables
FLOR.storage.migrate
FLOR.start

class AliceTasker < Flor::BasicTasker
  def task
    p '=================================================='
    p taskname
    reply
  end
end
FLOR.add_tasker(:alice, AliceTasker)

exid =
  FLOR.launch(%q{
    define one
      trace _
    define two
      trace _
    define three
      trace _
    define four
      trace _
    define five
      trace _
    define six
      trace _
    define seven
      trace _
    define eight
      trace _
    define nine
      trace _
    define ten
      trace _                                         # Error goes away with any of the below changes....
    define eleven                                     # works removing any function, one to eleven
      trace _
    #define twelve                                    # works adding a new function
    #  trace _

    set some_var true                                 # works removing the set
    on 'some_trap' count: 1                           # works removing this trap or even just the count
      alice 'baz'
    concurrence
      sequence                                        # works removing the sequence
        alice 'this one breaks' unless f.some_prop    # works removing the unless
        #task 'alice' 'foo'  unless f.some_prop       # works using `task 'alice' 'foo'` syntax instead of `alice 'foo'`
      alice 'working branch'                          # works removing the other concurrent branch
  })

r = FLOR.wait(exid, 'terminated')
pp r
```

`alice 'this one breaks'` is interpreted as:
Tasker: 'this one breaks'
Task name: 'nil'

instead of

Tasker: 'alice'
Task name: 'this one breaks'

You can change pretty much anything about the process and the problem will go away 😳🤔

The workaround is just to use the full task syntax: `task 'alice' 'this one doesn't break'`

```ruby
{"exid"=>"domain0-u0-20190920.0313.bolaladiba",
 "from"=>"0_13_0_0_1",
 "nid"=>"0_13_0_0_1",
 "sm"=>85,
 "payload"=>{"ret"=>"this one breaks"},
 "point"=>"failed",
 "fpoint"=>"task",
 "error"=>
  {"kla"=>"ArgumentError",
   "msg"=>"tasker \"this one breaks\" not found",
   "trc"=>
    ["/Users/ryanscott/.rvm/gems/ruby-2.6.3/gems/flor-0.18.0/lib/flor/unit/ganger.rb:57:in `task'",
     "/Users/ryanscott/.rvm/gems/ruby-2.6.3/gems/flor-0.18.0/lib/flor/unit/executor.rb:150:in `task'",
     "/Users/ryanscott/.rvm/gems/ruby-2.6.3/gems/flor-0.18.0/lib/flor/core/executor.rb:455:in `process'",
     "/Users/ryanscott/.rvm/gems/ruby-2.6.3/gems/flor-0.18.0/lib/flor/unit/executor.rb:75:in `block in do_run'",
     "/Users/ryanscott/.rvm/gems/ruby-2.6.3/gems/flor-0.18.0/lib/flor/unit/executor.rb:63:in `times'",
     "/Users/ryanscott/.rvm/gems/ruby-2.6.3/gems/flor-0.18.0/lib/flor/unit/executor.rb:63:in `do_run'",
     "/Users/ryanscott/.rvm/gems/ruby-2.6.3/gems/flor-0.18.0/lib/flor/unit/executor.rb:36:in `block in run'"],
   "cwd"=>"/Users/ryanscott/projects/flor_testing"},
 "_detail_msg_flag"=>true}
payload:
{"ret"=>
  "this one breaks"}
tree:
| 0_13_0_0_1 alice L33
| 0_13_0_0_1_0 _att L33
| 0_13_0_0_1_0_0 _sqs this one breaks L33
node:
{"nid"=>"0_13_0_0_1",
 "parent"=>"0_13_0_0",
 "payload"=>{"ret"=>nil},
 "status"=>
  [{"status"=>nil,
    "point"=>"execute",
    "ctime"=>"2019-09-20T03:13:04.875140Z"}],
 "ctime"=>"2019-09-20T03:13:04.875140Z",
 "mtime"=>"2019-09-20T03:13:04.886536Z",
 "heat0"=>"alice",
 "heat"=>["_tasker", {"tasker"=>"alice"}, -1],
 "heap"=>"task",
 "atts"=>[[nil, "this one breaks"]],
 "cnodes"=>[],
 "message"=>
  {"point"=>"receive",
   "exid"=>"domain0-u0-20190920.0313.bolaladiba",
   "from"=>"0_13_0_0_1_0",
   "nid"=>"0_13_0_0_1",
   "sm"=>84,
   "payload"=>{"ret"=>"this one breaks"},
   "er"=>2,
   "m"=>85,
   "pr"=>2,
   "consumed"=>"2019-09-20T03:13:04.887466Z"},
 "task"=>{"tasker"=>"this one breaks", "name"=>nil}}
nodes:
 0 [sequence,[[define,[[_att,[[one,[],2]],2],...  vars:one,two,three,four,five,six,seven,eight,nine,ten,eleven,some_var 
  0_12 [trap,[[_att,[[point,[],28],[_sqs,signal,2...  vars: 
  0_13 [concurrence,[[sequence,[[_unless,[[_ref,[...  
   0_13_0 [sequence,[[_unless,[[_ref,[[_sqs,f,33],[_...  
    0_13_0_0 [_unless,[[_ref,[[_sqs,f,33],[_sqs,some_pr...  
     0_13_0_0_1 [alice,[[_att,[[_sqs,"this one breaks",33]...   <---msg['nid']
   0_13_1 [task,[[_att,[[_sqs,alice,35]],35],[_att,[...  
7 nodes.
```

**Comment by Subtletree** [comment]
Feel like this might be something I'm missing rather that a bug. Either way I'm just using the mentioned workaround so feel free to close the issue and see if it ever comes up again, doubt it 😄

**Comment by jmettraux** [comment]
I want to fix that. It's a tough one. Thanks for coming up with the detailed report!

**Comment by jmettraux** [comment]
Enforcing `node['tree']` that solves it. I am now wondering why it ever worked. But this fix is true to the way I devised `node['tree']`.

Please tell me if there is anything wrong with this fix.

Thanks a lot!

**Comment by Subtletree** [comment]
Awesome, tricky fix! Fixes my original problem.
